### ISSUE TITLE
Customize section class

### ISSUE THREAD

**Issue by tp7309** [tp7309/flutter_sticky_and_expandable_list#1]
You can define an section class as you like, the only requirement is **implement ExpandableListSection**, this is to provide item data list in section. Like this:
```dart
class Section implements ExpandableListSection<Widget> {
  bool expanded;
  Widget header;
  List<Widget> items;

  @override
  List<Widget> getItems() {
    return items;
  }

  @override
  bool isSectionExpanded() {
    return expanded;
  }

  @override
  void setSectionExpanded(bool expanded) {
    this.expanded = expanded;
  }
}
``

**Comment by emvaized** [comment]
With this implementation of `Section` class I get the following error:
![Screenshot_20200316_234941](https://user-images.githubusercontent.com/37851576/76802656-d1e4f600-67e0-11ea-9f36-1e4431d66215.png)

**Comment by tp7309** [comment]
```dart
class Section implements ExpandableListSection<Widget> {}
//so:
SliverExpandableChildDelegate<Widget, Section>()
```
