### ISSUE TITLE
The SliverExpandableList isn't reversible

### ISSUE THREAD

**Issue by Ben-Baert** [tp7309/flutter_sticky_and_expandable_list#11]
It looks as if the SliverExpandableList isn't reversible (the ExpandableListView is). Is there a way to get this sort of behaviour (reversing and starting at the bottom)? Thanks!

**Comment by tp7309** [comment]
Just sort your data source(`sectionList` property). For example:
```dart
          setState(() {
            sectionList = sectionList.reversed.toList();
          });
```

**Comment by Ben-Baert** [comment]
That doesn't work unfortunately. It does indeed reverse the list, but that doesn't make the list start at the bottom like the reverse argument in `ListView` does. 

The concrete application is a sticky date chip like the one in Slack, with messages sorted by date as the `sectionList`.

**Comment by tp7309** [comment]
No support.
And I found a bug about `reverse` property in `ExpandableListView`, trying to fix it.

**Comment by tp7309** [comment]
No support yet.
