### ISSUE TITLE
怎么滚动到指定的section？

### ISSUE THREAD

**Issue by boai** [tp7309/flutter_sticky_and_expandable_list#14]
如题：怎么滚动到指定的section？

**Comment by tp7309** [comment]
目前还没出友好的方案。当前的支持可以看这个https://github.com/tp7309/flutter_sticky_and_expandable_list/issues/12#event-3519603566

**Comment by tp7309** [comment]
I have added an example of [scroll to index](https://github.com/tp7309/flutter_sticky_and_expandable_list/blob/master/example/lib/example_scroll_to_index.dart).
