### ISSUE TITLE
Cannot use custom model as ExpandableListSection Type

### ISSUE THREAD

**Issue by ydhnwb** [tp7309/flutter_sticky_and_expandable_list#17]
I want to create sectioned list with String as header title and BoardWithCategory as the child

Here is my code

BoardWithcategory model that i want to use as child
```
class BoardWithCategory {
  final Board board;
  final BoardCategoryData boardCategoryData;

  BoardWithCategory(this.board, this.boardCategoryData);
}
```

The board section,
```

class BoardSection implements ExpandableListSection<BoardWithCategory> {
  bool isExpanded;
  List<BoardWithCategory> boardWithCategory = List();
  String title;

  @override
  List<BoardWithCategory> getItems() => boardWithCategory;

  @override
  bool isSectionExpanded() => isExpanded;

  @override
  void setSectionExpanded(bool expanded) {
    this.isExpanded = expanded;
  }
}
```

How I use this in a page
```
BlocConsumer.....{

builder: (context, state){
return SliverExpandableList(
                builder: SliverExpandableChildDelegate<String, BoardSection>(
                    sectionList: _sectionList,
                    headerBuilder: _buildHeaderList,
                    controller: _controller,
                    itemBuilder: (context, sectionIndex, itemIndex, index) {
                      BoardWithCategory item = _sectionList[sectionIndex]
                          .boardWithCategory[itemIndex];
                      return ListTile(
                        leading: CircleAvatar(
                          child: Text("$index"),
                        ),
                        title: Text(item.boardCategoryData.name),
                      );
                    }),
              );

}
}
```

And here is the error
![Screenshot from 2020-08-24 13-34-19](https://user-images.githubusercontent.com/26734262/91011475-8eec4180-e60e-11ea-8db4-184c89866cd3.png)

The error says
**'BoardSection' doesn't extend 'ExpandableListSection<String>'.
Try using a type that is or is a subclass of 'ExpandableListSection<String>'**

I already extends the BoardSection with ExpandableListSection<BoardWithCategory> not ExpandableListSection<String>,
in the documentation it said that I need diamond interface <MyModelClass>, for this case im not using String as my model class but I get this error

**Comment by ydhnwb** [comment]
*I have found the solution :)

**Comment by tp7309** [comment]
I will add more comments here :)

**Comment by ydhnwb** [comment]
I thought the first param in diamond interface inside  SliverExpandbleChildDelegate<XXX, SomeAection> is the header.
