### ISSUE TITLE
Weird behavior of header item

### ISSUE THREAD

**Issue by ydhnwb** [tp7309/flutter_sticky_and_expandable_list#18]
I have some weird behavior.
If I scroll into some particular position like this gif below,
the header will move from top to the position where i click last item/position

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/26734262/91533866-cde60400-e93a-11ea-9992-684bb02ffe40.gif)

**Comment by tp7309** [comment]
Bug, and you can you the fixed version(**v0.2.3**) now.
