### ISSUE TITLE
During build all items are materialized

### ISSUE THREAD

**Issue by fryette** [tp7309/flutter_sticky_and_expandable_list#27]
Seems that the item builder always builds all items and that is a huge problem for long lists

**Comment by tp7309** [comment]
I have a plan to support sub listview at this weekend. Now each section is `Column` widget by default.

**Comment by fryette** [comment]
@tp7309 Thank you very much!

**Comment by tp7309** [comment]
@fryette I have update an [nested listview example](https://github.com/tp7309/flutter_sticky_and_expandable_list/blob/master/example/lib/example_nested_listview.dart), may be it can help you.

**Comment by fryette** [comment]
@tp7309 Will check today later!
Thanks! Really!
