### ISSUE TITLE
Is it possible to create a subsection in the Expandable List?

### ISSUE THREAD

**Issue by corusm** [tp7309/flutter_sticky_and_expandable_list#30]
First_Header
--> Second Header
-------> Items
--> Second Header
-------> Items

Is it possible to create a subsection in the Expandable List?

**Comment by tp7309** [comment]
Is First_Header need sticky?
Or is Second Header need sticky?

**Comment by corusm** [comment]
First header should be sticky

**Comment by tp7309** [comment]
Many solution, like [this example](https://stackoverflow.com/questions/50530152/how-to-create-expandable-listview-in-flutter), just replace ListView with `ExpandablListView`.
