### ISSUE TITLE
Is there way to scroll to the bottom or top programmatically?

### ISSUE THREAD

**Issue by nero-angela** [tp7309/flutter_sticky_and_expandable_list#33]
Thanks for making such a great package :)

I followed the [example_custom_section_animation](https://github.com/tp7309/flutter_sticky_and_expandable_list/blob/master/example/lib/example_custom_section_animation.dart), and It works fine. 👍

I have one question, is there way to scroll to the bottom or top programmatically?

**Comment by tp7309** [comment]
I have added an example of [scroll to index](https://github.com/tp7309/flutter_sticky_and_expandable_list/blob/master/example/lib/example_scroll_to_index.dart).
