### ISSUE TITLE
Not collapse

### ISSUE THREAD

**Issue by Saulmarti** [tp7309/flutter_sticky_and_expandable_list#34]
Im usign the 1.0.0-nullsafety.1 version, the view of items and the sticky header is working fine but when change the param expanded in onTap with:

`setState(() {
            sectionList[sectionIndex].setSectionExpanded(!section.isSectionExpanded());
 });
`
Did not collapse the items.

I debug that the onTap and the changes its applied, when i set initially the expanded true or false its working propertly, the problem is when change it, not trigger nothing.

Anyone more have this problem?

**Comment by tp7309** [comment]
Is [example](https://github.com/tp7309/flutter_sticky_and_expandable_list/blob/master/example/lib/example_listview.dart) work property?
