### ISSUE TITLE
Adding a separatorBuilder to the package's ListView example causes overlapping items

### ISSUE THREAD

**Issue by LewisHolliday** [tp7309/flutter_sticky_and_expandable_list#37]
**The argument passed to SliverExpandableChildDelegate:**
`separatorBuilder: (context, isHeader, index) {
                return Container();
              },`

**Steps to reproduce:**
1.  Expand some headers (Including header 0 and header 1 to allow scrolling.
2.  Close Header 0
3.  Expand Header 0
4.  Scroll down
This will make header 1's items overlap with header 0

**Visual:**

![issue_visual_example](https://user-images.githubusercontent.com/83846295/143530113-fa8e1d15-9b08-4aa4-8de4-3178c1e2b71e.gif)

**Tested on:**
Flutter 2.5.3, sticky_and_expandable_list: 1.0.2,
Android phone and Chrome.

**Comment by tp7309** [comment]
thank you for your feedback, fixed at `v1.0.3`.
