### ISSUE TITLE
展开一个Header#0 滑动一点点， 然后展开第二个的时候，Header#1时候，展开不是现实的第一个ListTitle#0这条数据

### ISSUE THREAD

**Issue by yj229201093** [tp7309/flutter_sticky_and_expandable_list#38]
![xin](https://user-images.githubusercontent.com/12807664/143974885-a2090098-50ca-4a1c-a217-9269d6b3a37d.gif)

Hello, I have a situation here. I'm going to expand one Header#0 by sliding a little bit, and then I'm going to expand the second one, and then I'm going to expand the first ListTitle#0 that's not actually real, and occasionally I'm going to flash. Don't know how to solve this?

demo Repetition can be

您好，我这边出现这种情况。展开一个Header#0 滑动一点点， 然后展开第二个的时候，Header#1时候，展开不是现实的第一个ListTitle#0这条数据，偶尔还有闪屏的情况。不知道这个怎么解决？

demo可复现

**Comment by yj229201093** [comment]
flutter 2.5.3,  sticky_and_expandable_list: ^1.0.2

**Comment by tp7309** [comment]
我晚上回去看下

**Comment by yj229201093** [comment]
好的 谢谢大佬

**Comment by tp7309** [comment]
找到了原因，我这两天想下怎么修改。

**Comment by yj229201093** [comment]
谢谢大佬。
还有请教下，有一个这样的场景。点击一个展开，其他都关闭。(每次只展开一个)。如果点击Header#5的话，Header#5展开，Header#5内容滑动到最顶部展开子组件。 这个扩展加属性好解决吗？

**Comment by tp7309** [comment]
示例：
```dart
Widget _buildHeader(
      BuildContext context, ExpandableSectionContainerInfo containerInfo) {
    ExampleSection section = sectionList[containerInfo.sectionIndex];
    return Builder(builder: (context1) {
      return InkWell(
          child: Container(
              color: Colors.lightBlue,
              height: 48,
              padding: EdgeInsets.only(left: 20),
              alignment: Alignment.centerLeft,
              child: Text(
                section.header,
                style: TextStyle(color: Colors.white),
              )),
          onTap: () {
            //toggle section expand state
            setState(() {
              sectionList.forEach((element) {
                element.setSectionExpanded(element == section);
              });
              WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
                Scrollable.ensureVisible(context1,
                    duration: Duration(milliseconds: 300));
              });

            });

          });
    });
  }
```

**Comment by yj229201093** [comment]
好的 谢谢！
这个问题：展开一个Header#0 滑动一点点， 然后展开第二个的时候，Header#1时候，展开不是现实的第一个ListTitle#0这条数据，偶尔还有闪屏的情况。这个原因是什么？好修改吗？ 因为这个插件很好用。辛苦大佬

**Comment by tp7309** [comment]
上面的写法也能解决第一个问题吧？你试下，框架里适配周末会腾出时间看

**Comment by yj229201093** [comment]
尝试了，还不能解决。还是一样。 不知道什么原因。

**Comment by yj229201093** [comment]
大佬 方便给一个联系方式请教一些问题不？

**Comment by tp7309** [comment]
那你加我wx吧，就这个用户名

**Comment by ArturoRen** [comment]
这个bug的问题没有完全解决，会出现闪缩情况
