### ISSUE TITLE
Null check operator exception on headerBuilder

### ISSUE THREAD

**Issue by swch01** [tp7309/flutter_sticky_and_expandable_list#39]
The `headerBuilder` parameter to `SliverExpandableChildDelegate` is nullable but its implementation expects a value.

https://github.com/tp7309/flutter_sticky_and_expandable_list/blob/9a152581a22e49e461b3f27c40eaaf137618a903/lib/src/sliver_expandable_list.dart#L172

**Comment by tp7309** [comment]
sectionBuilder or headerBuilder, at least one.

**Comment by swch01** [comment]
Perhaps this assert

https://github.com/tp7309/flutter_sticky_and_expandable_list/blob/9a152581a22e49e461b3f27c40eaaf137618a903/lib/src/sliver_expandable_list.dart#L135

could become

``` Dart
      : assert(
          (headerBuilder != null && sectionBuilder == null) ||
              (headerBuilder == null && sectionBuilder != null),
          'You must specify either headerBuilder or sectionBuilder.',
        ),
```

**Comment by tp7309** [comment]
ok, i will commit it.
