### ISSUE TITLE
Error ''owner!._debugCurrentBuildTarget == this': is not true  in Flutter v2.15.1

### ISSUE THREAD

**Issue by woodjobber** [tp7309/flutter_sticky_and_expandable_list#41]
Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4313 pos 14: 'owner!._debugCurrentBuildTarget == this':
is not true.

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4313 pos 14: 'owner!._debugCurrentBuildTarget == this':
is not true.
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2535 pos 20: '_debugCurrentBuildTarget == context': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2535:20)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2539:12)
#4      RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#5      WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#6      WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
#7      _rootRun (dart:async/zone.dart:1420:47)
#8      _CustomZone.run (dart:async/zone.dart:1328:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#11     _rootRun (dart:async/zone.dart:1428:13)
#12     _CustomZone.run (dart:async/zone.dart:1328:19)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
#14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by tp7309** [comment]
Paste an example?
I will test it an this weekend.

**Comment by tp7309** [comment]
flutter lastest version is v2.11....
I has test lastest version, no issue.
