### ISSUE TITLE
Migrate to 3.0.0

### ISSUE THREAD

**Issue by M2dL1fe** [tp7309/flutter_sticky_and_expandable_list#42]
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/sticky_and_expandable_list-1.0.3/lib/src/expandable_section_container.dart:170:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
                     ^
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/sticky_and_expandable_list-1.0.3/lib/src/sliver_expandable_list.dart:410:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^

**Comment by tp7309** [comment]
done, try `1.1.0` version.

**Comment by M2dL1fe** [comment]
nice @tp7309

**Comment by fullflash** [comment]
same error with lates version.

```
[        ] ../../../../.pub-cache/hosted/pub.dartlang.org/sticky_and_expandable_list-1.1.0/lib/src/expandable_section_container.dart:170:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/src/expandable_section_container.dart:170
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../SDK_all/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
[        ] Try calling using ?. instead.
[        ]       WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
[        ]                               ^^^^^^^^^^^^^^^^^^^^
```

**Comment by tp7309** [comment]
@fullflash see https://github.com/tp7309/flutter_sticky_and_expandable_list/issues/43.
