### ISSUE TITLE
在android设备上运行报错

### ISSUE THREAD

**Issue by weigoudan** [tp7309/flutter_sticky_and_expandable_list#44]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:stripDebugDebugSymbols'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by tp7309** [comment]
按错误提示搜索下，装下Android NDK.
