### ISSUE TITLE
Expand/Collapse All - New feature request 

### ISSUE THREAD

**Issue by kostaa** [tp7309/flutter_sticky_and_expandable_list#5]
First of all thanks you for this library. I have been waiting for one of these for quite some time :-)   

One thing I think would be very useful is to the ability to expand/collapse all sections at the same time  so the user does not have to do it one by one which is quite tedious especially for longer lists.

**Comment by tp7309** [comment]
I'm also glad you used this library ^_^
Expand state is stored in **section** model, so just update all section expand state.
```dart
  setState(() {
    sectionList.forEach(
        (section) => section.setSectionExpanded(!section.isSectionExpanded()));
  });
```
Is this what you need?

**Comment by kostaa** [comment]
Yes thanks that is exactly what I need.
