### ISSUE TITLE
[Bug] sliver sticky header does not work

### ISSUE THREAD

**Issue by Cierra-Runis** [tp7309/flutter_sticky_and_expandable_list#50]
It doesn't work at `Windows` with error:

```
flutter: ExpandableSectionContainer _refreshContainerLayoutOffsets reason:zero size
```

![image](https://github.com/tp7309/flutter_sticky_and_expandable_list/assets/29329988/bc7f7386-75ef-4d11-8a53-12b2806db19c)

**Comment by tp7309** [comment]
need more detail info.
windows version 
flutter version
emulator version
example  code

**Comment by Cierra-Runis** [comment]
- windows version : Windows11
- flutter version : 3.10.5
- emulator : not using
- example code : [here](https://github.com/Cierra-Runis/mercurius/blob/master/lib/widgets/diary/views/list/diary_list_view_widget.dart#L52-L82)

It's fine at `Android`, but doesn't work at `Windows`

**Comment by 1446809932** [comment]
I also encountered this issue on Android
setState(() {
  sectionList[i].setSectionExpanded(true);
});

flutter (30418): ExpandableSectionContainer _refreshContainerLayoutOffsets reason:zero size
flutter (30418): ExpandableSectionContainer clearContainerLayoutOffsets
flutter (30418): ExpandableSectionContainer clearContainerLayoutOffsets
flutter (30418): ExpandableSectionContainer _refreshContainerLayoutOffsets reason:zero size

**Comment by 1446809932** [comment]
android version : 13
flutter version :  3.7.12
emulator version : not using
example code : 
setState(() {
      sectionList[i].setSectionExpanded(true);
});

**Comment by 1446809932** [comment]
没错，是我自己错的，上面那些都是自己状态管理写错了

**Comment by tp7309** [comment]
好的👍
