### ISSUE TITLE
Sticky header is not working after changing navigation tab

### ISSUE THREAD

**Issue by Gazizbek** [tp7309/flutter_sticky_and_expandable_list#51]
At the first launch, everything works perfectly. After changing the navigation tab, it stops working

Flutter 3.16.0
sticky_and_expandable_list: ^1.1.3

https://github.com/tp7309/flutter_sticky_and_expandable_list/assets/43266026/45348ae5-3e77-4340-be49-2e6741aaf627

**Comment by tp7309** [comment]
try trigger force refresh when navigation tab changed. for example:
1. change sectionList.
2. call `setState()` for trigger layout.
