### ISSUE TITLE
scroll_to_index

### ISSUE THREAD

**Issue by lcm1475** [tp7309/flutter_sticky_and_expandable_list#52]
If I want to scroll to the 100th item the first time, it won't happen because the 100th item hasn't been rendered yet, right? Is there any solution? This library is great. I have given you a little reward

**Comment by tp7309** [comment]
thank you.
see this example，no perfect solution .
https://github.com/tp7309/flutter_sticky_and_expandable_list/blob/master/example/lib/example_scroll_to_index.dart

**Comment by lcm1475** [comment]
我看了这个例子了，一个一个的跳转没问题，但是如果我想第一次就跳转到第100个是不行的 我就是在这个例子的基础上试的，我猜测应该是ListView的加载机制导致第100个还没有加载出来，所以跳不过去，这个问题有解决办法吗

**Comment by tp7309** [comment]
搜一些基于scrollable_positioned_list 做的库吧，能达到要求。

**Comment by lcm1475** [comment]
好 谢谢
