### ISSUE TITLE
与 flutter_slidable 插件配合使用任何时候最多显示一个滑动展开时，heder 滑到顶端固定不了

### ISSUE THREAD

**Issue by xRuby** [tp7309/flutter_sticky_and_expandable_list#53]
是 StatefulWidget 传值 State 的问题，😂   不过确实有一个问题，就是 与 flutter_slidable 插件配合使用任何时候最多显示一个滑动展开时，heder 滑到顶端固定不了。

**Comment by tp7309** [comment]
你用源代码调调吧，最近没时间修复🤣

**Comment by xRuby** [comment]
> 你用源代码调调吧，最近没时间修复🤣

等你空了来吧，或则我先把功能完善了来😂

**Comment by xRuby** [comment]
一次性加载list没有这个BUG，但是用了上拉加载，下拉刷新会有这个bug

**Comment by xRuby** [comment]
算了我用一次性加载了😂
