### ISSUE TITLE
items.length > 1000的时候 ，点击展开关闭，非常卡，应是这个数越大会越卡

### ISSUE THREAD

**Issue by liaoli** [tp7309/flutter_sticky_and_expandable_list#7]

**Comment by tp7309** [comment]
每个分组是作为一个控件放在SliverList中，每个分组中的控件目前是一次性创建出来的，不支持这么大的数据，找时间我优化下。

**Comment by tp7309** [comment]
@liaoli 
如果分组有大量数据的话，是不是只需要一个固定头部的效果，而不需要不同分组切换的效果。
如果需求是这样子的话可以直接用CustomScrollView+SliverAppBar(pinned:true)实现。

**Comment by tp7309** [comment]
规划在下一个大版本中，估计6月份。

**Comment by liaoli** [comment]
问题还没解决啊

**Comment by tp7309** [comment]
没有，转需求，正在开发中o.o。
