### ISSUE TITLE
Jump scroll to header section

### ISSUE THREAD

**Issue by guitar09** [tp7309/flutter_sticky_and_expandable_list#8]
Is it possible to scroll the list to a specific index in the header(pinned)?

for example: 
scrollControler.jumpTo(sectionIndex);

sorry my bad english

**Comment by tp7309** [comment]
Sorry, the current version does not support jump to specified items. There are the following temporary solutions:
```dart
  var _controller = ExpandableListController();
  var _listController = ScrollController();

        onTap: () {
          bool hasSeparator = false;
          int indexInListView = hasSeparator ? sectionIndex * 2 : sectionIndex;
          //get section offset, can not get the offset which not visible on screen.
          double offset = _controller.containerOffsets[indexInListView];
          _listController.animateTo(offset,
              duration: Duration(microseconds: 1000), curve: Curves.linear);
        });
```

**Comment by daviresio** [comment]
> p
where i can associate this value to ExpandableListView?
` var _controller = ExpandableListController();`

because if i define this variable and print 
`_controller.containerOffsets;`

i received a empty array

**Comment by tp7309** [comment]
see [example](https://github.com/tp7309/flutter_sticky_and_expandable_list/blob/master/example/lib/example_animable_header.dart).

**Comment by tp7309** [comment]
I have added an example of [scroll to index](https://github.com/tp7309/flutter_sticky_and_expandable_list/blob/master/example/lib/example_scroll_to_index.dart).
